spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.jpmc.midascore.foundation"
      group-id: midas-core-group
      auto-offset-reset: earliest
general:
  kafka-topic: transactions

datasource:
  url: jdbc:h2:mem:testdb
  driver-class-name: org.h2.Driver
  username: sa 
  password: password

jpa: 
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: true
  show-sql: true
  properties:
    hibernate:
      format_sql: true

h2: 
  console:
    enabled: true

logging:
  level:
    com.jpmc.midascore: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
    root: INFO

server:
  port: 33400